<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\UUPMediaCreator\src\UnifiedUpdatePlatform.Services.WindowsUpdate.Downloads\UnifiedUpdatePlatform.Services.WindowsUpdate.Downloads.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="NuGetizer" Version="1.5.1" />
    </ItemGroup>

</Project>
