<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>$(AppTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU;x64;x86;ARM64;x64</Platforms>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Remove="NuGetizer" />
        
        <PackageReference Include="CliWrap" Version="3.10.5" />
        <PackageReference Include="Meziantou.Framework.CommandLine" Version="4.0.2" />
        <PackageReference Include="Microsoft.Build" Version="18.10.1" ExcludeAssets="runtime" />
        <PackageReference Include="Microsoft.Build.Locator" Version="1.10.12" />
        <PackageReference Include="Microsoft.Build.Runtime" Version="18.10.1" ExcludeAssets="runtime" />
        <PackageReference Include="Microsoft.Msix.Utils" Version="2.1.1" />
        <PackageReference Include="Spectre.Console" Version="0.57.2" />

        <ProjectReference Include="..\FluentStore.SDK\FluentStore.SDK.csproj" />
    </ItemGroup>

</Project>
