<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(AppTargetFramework)</TargetFramework>
        <TargetPlatformMinVersion>$(MinWindowsVersion)</TargetPlatformMinVersion>
        <Platforms>AnyCPU;x64;x86;ARM64</Platforms>
        <AssemblyVersion>$(FluentStoreVersion)</AssemblyVersion>
        <FileVersion>$(AssemblyVersion)</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.WinUI.Collections" Version="8.2.251219" />

        <ProjectReference Include="..\API\FluentStoreAPI\FluentStoreAPI.csproj" />
        <ProjectReference Include="..\FluentStore.SDK\FluentStore.SDK.csproj" />
        <ProjectReference Include="..\FluentStore.Services\FluentStore.Services.csproj" />
        <ProjectReference Include="..\API\MicrosoftStore\Microsoft.Marketplace.Storefront.Contracts.csproj" />
    </ItemGroup>

</Project>
